### ISSUE TITLE
Lista zakupowa - dodawanie

### ISSUE THREAD

**Issue by Modziak** [SebastianLasisz/Przepisy#2]
Przy próbie dodania drugiego i każdego kolejnego składnika strona wysiada (i mówi grzecznie "nie")

**Comment by Modziak** [comment]
Request Method: POST
Request URL:    http://sedi.pythonanywhere.com/add_shopping_list/
Django Version: 1.9.4
Exception Type: UnboundLocalError
Exception Value:  
local variable 'recipe_form' referenced before assignment
Exception Location: /home/Sedi/przepisy/Przepisy/build/website/website/views.py in create_shopping_list, line 361
Python Executable:  /usr/local/bin/uwsgi
Python Version: 2.7.6
Python Path:  
['/var/www',
 '.',
 '',
 '/var/www',
 '/home/Sedi/.virtualenvs/myvirtualenv/lib/python2.7',
 '/home/Sedi/.virtualenvs/myvirtualenv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/Sedi/.virtualenvs/myvirtualenv/lib/python2.7/lib-tk',
 '/home/Sedi/.virtualenvs/myvirtualenv/lib/python2.7/lib-old',
 '/home/Sedi/.virtualenvs/myvirtualenv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/Sedi/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages',
 '/home/Sedi/.virtualenvs/myvirtualenv/lib/python2.7/site-packages',
 '/home/Sedi/przepisy/Przepisy/build/website']
Server time:    Wed, 18 May 2016 10:40:31 +0000

**Comment by SediDeVone** [comment]
Zrobione.
