### ISSUE TITLE
Składniki - ogólnie

### ISSUE THREAD

**Issue by Modziak** [SebastianLasisz/Przepisy#7]
(wymaga to dosyć mocnego przeprojektowania systemu)
- stworzyć kategorie produktów z przypisanymi do nich możliwymi jednostkami
- dodać na rzutowanie na jedną ogólnie przyjętą jednostkę do przechowywania w bazie danych
- dodać rzutowanie na wybrany przez użytkownika system jednostkowy (np wszystkie składniki w kg itd.)
- drop down list na stronie do wyboru jednostki
- drop down list (z wyszukiwaniem) z produktami

**Comment by SediDeVone** [comment]
Zrobione
